SWIFT model simulation scaling measures
=================

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"', fig.align="center", fig.width=10, fig.height=8, dev='png')
```

```{r, eval=FALSE, include=FALSE}
library(swiftdev)
thisPkgDir <- file.path('f:/src/github_jm/hwrs2015')
if(file.exists(thisPkgDir))
{
  setwd(file.path(thisPkgDir, 'reports'))
  purlAll('.','.')
}
```

# About this document

This document was generated from an R markdown file on `r as.character(Sys.time())`.

# Methods

* system size
* number of time steps
* number of input time series
* number of output time series
* level of parallel runs (multi-threading)

```{r}
cases <- expand.grid(so=1:4, years=c(2,5,10,20,30), threads=1:6)
```

```{r}
library(ophct)
library(microbenchmark)
library(dplyr)
library(DiagrammeR)
```

```{r}
simulStart <- '2000-01-01'
simulEnd <- '2009-12-31'
sSpan <- paste0(simulStart, '/', simulEnd)

rain <- sampleSeries('Ovens', 'rain')[sSpan]
evap <- sampleSeries('Ovens', 'evap')[sSpan]
flow <- sampleSeries('Ovens', 'flow')[sSpan]

head(index(rain))

extendTs <- function(tSeries) {
  d <- as.vector(tSeries)
  d <- rep(d, 4)
  res <- xts(d, order.by=(index(tSeries)[1] + 3600*(0:(length(d)-1))))
  return(res['2000-01-01/2029-12-31'])
}

rain <- extendTs(rain)
evap <- extendTs(evap)
flow <- extendTs(flow)

```

```{r}
numLinks <- function(streamOrder=1) {
  sum(2**(1:streamOrder))
}

nReps <- 10

defineNetwork <- function(streamOrder=1, runoffModel='AWBM') {
# o    o  o    o 
#  \  /    \  /    stream order 2
#    o      o
#     \    /      stream order 1
#       o
  # numLinks(0) = 0
  # numLinks(1) = 2
  # numLinks(2) = 4
  # numLinks(n) = numLinks(n-1)*2
  # so:
  # numLinks = sum(1->n)(2**n)

  # numNodes(0) = 1
  # numNodes(1) = 2
  # numNodes(2) = 4
  # numNodes(n) = numNodes(n-1)*2
  # numNodes = sum(1->n)(2**n) + 1

  nl <- numLinks(streamOrder)
  linkIds <- paste0("link_id_", 1:nl)
  nodeIds <- paste0("node_id_", 1:(nl+1))

  defn <- list(
    nodeIds=nodeIds,
    nodeNames = paste0(nodeIds, '_name'),
    linkIds=linkIds,
    linkNames = paste0(linkIds, '_name'),
    fromNode = nodeIds[2:length(nodeIds)], # 2,3,4,5,6,7,8,...
    toNode = rep(nodeIds, each=2)[1:(length(nodeIds)-1)], # 1,1,2,2,3,3,4,4...
    areasKm2 = rep(1.0, nl),
    runoffModel = runoffModel
  )
  defn
}

mkModelStructure <- function(defn) {
  createCatchment(
      defn$nodeIds, defn$nodeNames, 
      defn$linkIds, defn$linkNames, 
      defn$fromNode, defn$toNode, 
      defn$runoffModel, defn$areasKm2)
}
mkModel <- function(streamOrder, tstep='hourly') {
  simulation <- mkModelStructure(defineNetwork(streamOrder))
  setSimulationSpan(simulation, start(rain), end(rain))
  setSimulationTimeStep(simulation, tstep)
  simulation <- swapModel(simulation, 'MuskingumNonLinear', 'channel_routing')
  return(simulation)
}

cpSimul <- function(s) {
  return(clrCall(s, 'CloneModel'))
}
```
# Assess the impact of adding input time series and output time series.
```{r}

baseline <- mkModel(3) 

s1 <- cpSimul(baseline)
sIds <- getSubareaIds(s1)

for (s in sIds) {
  playSubareaInput(s1, input=rain, s, 'Rainfall')
}
s2 <- cpSimul(s1)
for (s in sIds) {
  playSubareaInput(s2, input=evap, s, 'Evapotranspiration')
}

s3 <- cpSimul(s2)
for (s in sIds) { recordState(s3, paste('subarea', s, 'Runoff', sep='.')) }

s4 <- cpSimul(s3)
for (s in sIds) { recordState(s4, paste('subarea', s, 'Baseflow', sep='.')) }

systems <- list(baseline, s1, s2, s3, s4)
f <- function(i) {execSimulation(systems[[i]])}

# mb <- microbenchmark(f(1), f(2), f(3), f(4), f(5), times=nReps, control = list(order='block'))
# plot(mb, ylab = 'time (ns)')

getMeanTime <- function(mbench) {
  m <- as.data.frame(mbench)
  m_g <- group_by(m, expr)
  summarise(m_g, time = mean(time, na.rm = TRUE))
}


mkTypical <- function(streamOrder, years=10, tstep='hourly') {
  sim <- mkModel(streamOrder) 
  sIds <- getSubareaIds(sim)
  simulStart <- '2000-01-01'
  simulEnd <- paste0(2000+years-1, '-12-31')
  sSpan <- paste0('2000-01-01/',2000+years-1, '-12-31')
  rain <- rain[sSpan]
  evap <- evap[sSpan]
  for (s in sIds) {
    playSubareaInput(sim, input=rain, s, 'Rainfall')
    playSubareaInput(sim, input=evap, s, 'Evapotranspiration')
  }
  setSimulationSpan(sim, start(rain), end(rain))
  setSimulationTimeStep(sim, tstep)
  recordState(sim, 'Catchment.StreamflowRate')
  return(sim)
}

clrLoadAssembly('f:/src/github_jm/hwrs2015/ParallelSwift/bin/Debug/ParallelSwift.dll')

runParallel <- function(simulation, nthreads=1L, reps=1L) {
	return(clrCallStatic('ParallelSwift.SwiftRunTests', 'ParallelRun', simulation, nthreads, reps))
}
		
runCase <- function(streamOrder, years=10L, nthreads=1L, reps=1L) {
  s <- mkTypical(streamOrder, years)
  runParallel(s, nthreads=nthreads, reps=reps)
}

runCase(streamOrder=3L, years=10L, nthreads=1L, reps=1L)





systems <- lapply( 1:4, function(i) { mkTypical(i) } )

mb <- microbenchmark(f(1),f(2),f(3),f(4), times=nReps, control = list(order='block'))


plot(mb, ylab = 'time (ns)')
m <- getMeanTime(mb)
plot( sqrt(time) ~ expr, data=m)

d <- getCatchmentDotGraph(s4)
DiagrammeR(d)
```
